### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by Ge0rges** [conradev/WWDC2014#2]
Hey Conrad! I was thinking of applying this year to WWDC and wanted to see some examples of applications. Seems like yours doesn't build due to script errors in the 'Discount' Target as well as missing files. Would appreciate if you could fix this or provide a quick demo of your app.

Thanks.

**Comment by conradev** [comment]
I just fixed the build on Xcode 6.3+ with the latest commit. What most likely happened was that you didn't clone the required submodules. Run this command within the project's directory, and it should compile fine:

```bash
git submodule update --init
```

**Comment by Ge0rges** [comment]
Awesome thanks. 

Just curious will you be going this year?

**Comment by conradev** [comment]
I hope to be, yes!
